AWSTemplateFormatVersion: '2010-09-09'
Description: Map-reduce implentation using Lambda, S3 and SQS in Node
Globals:
  Function:
    Environment:
      Variables:
        S3_BUCKET:
          Ref: S3MRBucket
        SQS_AGGREGATOR_TRIGGER_URL:
          Ref: SQSAggregatorTriggerQueue
        SQS_AGGREGATOR_WATCHER_URL:
          Ref: SQSAggregatorWatcherQueue
        SQS_MAPPER_URL:
          Ref: SQSMapperInputQueue
        SQS_MAPPER_WATCHER_URL:
          Ref: SQSMapperWatcherQueue
        SQS_REDUCER_URL:
          Ref: SQSReducerInputQueue
        SQS_REDUCER_WATCHER_URL:
          Ref: SQSReducerWatcherQueue
Resources:
  AggregatorFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/e60112bcec44c0586e422b5824ce13f2
      Events:
        SQSAggregatorRequestedEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::GetAtt:
              - SQSAggregatorTriggerQueue
              - Arn
          Type: SQS
      Handler: reducer/reducer.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
    Type: AWS::Serverless::Function
  AggregatorWatcherFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/3ffefae50f4ede51ea286daadce6d800
      Events:
        SQSAggregatorWatcherEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::GetAtt:
              - SQSAggregatorWatcherQueue
              - Arn
          Type: SQS
      Handler: aggregator-watcher/aggregator-watcher.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
    Type: AWS::Serverless::Function
  DriverFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/9b580da07710267077a0365fb920ab47
      Handler: driver/driver.default
      MemorySize: 2048
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 360
      Tracing: Active
    Type: AWS::Serverless::Function
  MapperFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/0f48d62d6541e02d362d3757276c0bf5
      Events:
        SQSMapperRequestedEvent:
          Properties:
            BatchSize: 5
            Queue:
              Fn::GetAtt:
              - SQSMapperInputQueue
              - Arn
          Type: SQS
      Handler: mapper/mapper.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
    Type: AWS::Serverless::Function
  MapperWatcherFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/6a15c39905d46f9363f8b57275545bba
      Events:
        SQSAggregatorWatcherEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::GetAtt:
              - SQSMapperWatcherQueue
              - Arn
          Type: SQS
      Handler: mapper-watcher/mapper-watcher.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
      Tracing: Active
    Type: AWS::Serverless::Function
  ReducerFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/e60112bcec44c0586e422b5824ce13f2
      Events:
        SQSReducerRequestedEvent:
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - SQSReducerInputQueue
              - Arn
          Type: SQS
      Handler: reducer/reducer.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
    Type: AWS::Serverless::Function
  ReducerWatcherFunction:
    Properties:
      CodeUri: s3://com.zerotoheroes.artifact/370b19849f2ce3045857475fbf05d0ae
      Events:
        SQSAggregatorWatcherEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::GetAtt:
              - SQSReducerWatcherQueue
              - Arn
          Type: SQS
      Handler: reducer-watcher/reducer-watcher.default
      MemorySize: 512
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSESFullAccess
      - AmazonSNSReadOnlyAccess
      - AmazonSQSFullAccess
      - AmazonS3FullAccess
      Runtime: nodejs10.x
      Timeout: 600
      Tracing: Active
    Type: AWS::Serverless::Function
  S3MRBucket:
    Properties:
      BucketName: com.zerotoheroes.mr
    Type: AWS::S3::Bucket
  SQSAggregatorTriggerQueue:
    Properties:
      QueueName: mr-sqs-aggregator-trigger
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
  SQSAggregatorWatcherQueue:
    Properties:
      QueueName: mr-sqs-aggregator-watcher
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
  SQSMapperInputQueue:
    Properties:
      QueueName: mr-sqs-mapper
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
  SQSMapperWatcherQueue:
    Properties:
      QueueName: mr-sqs-mapper-watcher
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
  SQSReducerInputQueue:
    Properties:
      QueueName: mr-sqs-reducer
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
  SQSReducerWatcherQueue:
    Properties:
      QueueName: mr-sqs-reducer-watcher
      VisibilityTimeout: 601
    Type: AWS::SQS::Queue
Transform: AWS::Serverless-2016-10-31
